name: ${project.name}
version: ${project.version}
main: org.shanerx.tradeshop.TradeShop
api-version: 1.14
load: POSTWORLD
depend: [WorldGuard]

authors: [Lori00, KillerOfPie]
description: ${project.description}
website: ${project.url}

commands:
  negozi:
    description: Comando di gestione dei negozi
    aliases: [n]
